### ISSUE TITLE
I cannot run the program it says

### ISSUE THREAD

**Issue by Alpo3strong** [CodeWithJoe2020/AddressCleanerBot#9]
PS C:\Users\alpo3strong\alpo> node bot.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\alpo3strong\alpo\bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\alpo3strong\alpo> 
How can this be solved and also if you run cd" directory" after creating it it says that it does not find it

**Comment by 4thefade** [comment]
> npm i ethers
